{% set name = "pyiron_gui" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_gui-{{ version }}.tar.gz
  sha256: e979e6aea39eb58bf8499f493b127958a328a6bec7200dde0489910ab7a7994d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - ipywidgets >=7.6.3
    - pyiron_base >=0.2.17
    - pyiron_atomistics >=0.2.17
    - numpy >=1.21.0
    - pandas >=1.2.5
    - matplotlib-base >=3.4.2

test:
  imports:
    - pyiron_gui
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_gui
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extended graphical user interface (GUI) for pyiron the integrated development environment (IDE)
  description: |
    extended graphical user interface (GUI) for pyiron the integrated development environment (IDE)
  doc_url: https://github.com/pyiron/pyiron_gui
  dev_url: https://github.com/pyiron/pyiron_gui

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - muh-hassani
    - niklassiemer
